### ISSUE TITLE
Middleware cannot be sent between threads safely

### ISSUE THREAD

**Issue by PeterPierinakos** [jacob-pro/actix-extensible-rate-limit#1]
I am trying to use your middleware in order to rate limit my app. However, it causes some compilation errors with actix_web. I made a reproducible example repository to help fix the issue because I don't know if it's a problem from my end. I am using the redis feature.

Here is the reproducible repository containing the code: https://github.com/PeterPierinakos/reproducible-build

Dependencies:
```
actix-web = "4.0.1"
redis = "0.21.5"
actix-extensible-rate-limit = { version = "0.2.1", features = ["redis"] }
```

Compilation error:
```
error[E0277]: `Rc<(dyn Fn(StatusCode) -> bool + 'static)>` cannot be sent between threads safely
  --> src/main.rs:8:1
   |
8  |   #[actix_web::main]
   |   ^^^^^^^^^^^^^^^^^^ `Rc<(dyn Fn(StatusCode) -> bool + 'static)>` cannot be sent between threads safely
...
20 |       HttpServer::new(|| {
   |  _____________________-
21 | |         App::new()
22 | |             .wrap(middleware)
23 | |     })
```

I tried following the documentation. What's the issue?

**Comment by jacob-pro** [comment]
Yeah so the middleware and SimpleInputFunctionBuilder are not Send (because they contain functions wrapped in Rc).

If you move creating them into the Http Factory (which is run once per worker thread) it should work:

```
    HttpServer::new(|| {
        let input = SimpleInputFunctionBuilder::new(Duration::from_secs(60), 5)
            .real_ip_key()
            .build();
        let middleware = RateLimiter::builder(backend.clone(), input).add_headers().build();
        App::new()
            .wrap(middleware)
    })    
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

[Works for me here](https://github.com/jacob-pro/calpol/blob/master/src/main.rs#L79)

~~However I can see how this is not necessarily ergonomic - so I'm happy to change the [Rc to Arc here](https://github.com/jacob-pro/actix-extensible-rate-limit/blob/master/src/middleware/mod.rs#L25-L27) - would that be helpful?~~

Edit: I think it is probably best to keep as it is, otherwise the various functions would have to have Send bounds as well - I think the pattern of initializating once per Actix worker / in the Http factory is consistent with the ecosystem.

**Comment by PeterPierinakos** [comment]
Thank you man this works well now. And yes, it would be helpful if you did that. By the way I see that your repo is pretty new so adding some detailed examples to the docs for basic usage would be helpful ;)

Closing issue, deleting reproducible example repository.

**Comment by tglman** [comment]
Hi, 

I had the same problem, and I have only one small concern: with the in memory store, it would be created one instance of the in memory store for each worker, which increase the actually limits, so for that case I think would be better if the store was an instance that existed outside of the initialization method.

Regards

**Comment by jacob-pro** [comment]
@tglman Is that not what the example shows already?

```
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    // A backend is responsible for storing rate limit data, and choosing whether to allow/deny requests
    // * CREATES ONE STORE INSTANCE FOR THE WHOLE APPLICATION HERE *
    let backend = InMemoryBackend::builder().build();

    HttpServer::new(move || {
        // Assign a limit of 5 requests per minute per client ip address
        let input = SimpleInputFunctionBuilder::new(Duration::from_secs(60), 5)
            .real_ip_key()
            .build();
        let middleware = RateLimiter::builder(backend.clone(), input)
            .add_headers()
            .build();
        App::new().wrap(middleware)
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

The `InMemoryBackend` is just created once at application startup, any clones you make of it are just cloning the reference, it is still the same store.

**Comment by tglman** [comment]
Hi,

Thanks just figured that out myself, thank you anyway ! 

Regards
